toolbar:
  logo: "/assets/images/logo.png"
  title: "Daniel Kim Lab"
  subtitle: "RNA+HEALTH"
  menu:
  - title: "About"
    url: "#about"
  - title: "Research"
    url: "#research"
  - title: "Members"
    url: "#members"
  - title: "Publications"
    url: "#publications"
  - title: "Contact"
    url: "#contact"

about:
  background: "/assets/images/biomed.jpg"
  short: Studying the noncoding transcriptome to develop RNA liquid biopsy technology for precision health and early detection of diseases.
  long: Over 75% of the 3 billion base pairs in our genome are transcribed into RNA, yet only 1-2% are translated into proteins. Our lab investigates this noncoding RNA “dark matter” of unknown function. We use transcriptomic technologies to discover and understand the features and functions of these noncoding RNAs. Specifically, our lab studies how RAS signaling regulates the expression and secretion of the noncoding transcriptome during the earliest stages of development and cancer. We are leveraging these discoveries to develop non-invasive RNA liquid biopsy technology for precision health and early detection of diseases such as cancer.
  location: UC Santa Cruz

research:
- title: Regulation of transposable elements and RNA secretion
  description: We employ tissue culture models of disease to study how oncogenic signaling like mutant KRAS impact the development of human induced pluripotent stem cells through RNA sequencing, and how these changes in the transcriptome are reflected in the secreted exosomes.
  image: /assets/images/teasers/sree_wetlab.jpg
- title: Modeling cancer transcriptomic signatures in the blood plasma of patients
  description: We are studying the viability of RNA-sequencing based cancer tests by training advanced machine larning models on data derived from human blood plasma of patients with cancer towards the development of a non-invasive RNA liquid biopsy technology.
  image: /assets/images/teasers/roman_drylab.jpg

members:
- name: Daniel Kim
  position: PI
  image: /assets/images/members/daniel_kim.jpg
  orcid: xxx
  linkedin: xxx
  bsky: xxx
- name: Andy Davidson
  position: PhD Candidate
  image: /assets/images/members/andy_davidson.png
  orcid: xxx
  linkedin: xxx
  bsky: xxx
- name: Vikas Peddu
  position: PhD Candidate
  image: /assets/images/members/vikas_peddu.jpg
  orcid: xxx
  linkedin: xxx
  bsky: xxx
- name: Alex Hill
  position: PhD Student
  image: /assets/images/members/alex_hill.jpg
  orcid: 0000-0001-8903-0297
  linkedin: alexanderdhill
  bsky: https://bsky.app/profile/alexdhill.xyz
- name: Connor Mattingly
  position: PhD Student
  image: /assets/images/members/connor_mattingly.png
  orcid: ""
  linkedin: ""
  bsky: ""
- name: Shivani Mandalaparthi
  position: Undergraduate
  image: /assets/images/members/-
  orcid: ""
  linkedin: "test"
  bsky: ""
- name: Piper Mahn
  position: Undergraduate
  image: /assets/images/members/-
  orcid: ""
  linkedin: ""
  bsky: ""
- name: Delaney Boman
  position: Undergraduate
  image: /assets/images/members/-
  orcid: ""
  linkedin: ""
  bsky: ""

alumni:
- name: Roman Reggiardo
  position: Post-doctoral Fellow/Stanford RAMP
  image: /assets/images/members/roman_reggiardo.jpg
- name: Sree Lakshmi Velandi Maroli
  position: Scientist/HAYA Therapeutics
  image: /assets/images/members/sree_lakshmi.jpg
- name: Daniel Arriaza
  position: Life Science Research/Stanford RAMP
  image: /assets/images/members/daniel_arriaza.jpg
  orcid: xxx
  linkedin: xxx
  bsky: xxx
- name: Mady Chertkow
  position: PhD Student/UC Berkeley
  image: /assets/images/members/mady_chertkow.jpg
- name: Queenie Li
  position: Bioinformatics Analyst/Tempus
  image: /assets/images/members/queenie_li.jpg

sponsors:
- name: Baskin Engineering
  image: /assets/images/logos/BE_logo.jpg
- name: UCSC Genomics Institute
  image: /assets/images/logos/GI_logo.png
- name: UCSC RNA Center
  image: /assets/images/logos/RNAC_logo.jpg
- name: UCSC IBSC
  image: /assets/images/logos/IBSC_logo.png
- name: NIH
  image: /assets/images/logos/NIH_logo.png
- name: TRDRP
  image: /assets/images/logos/TRDRP_logo.jpg

news:
- title: ""
  date: ""
  description: ""
  embed: ""

publications:
- title: "Title of the publication"
  authors: "Author1, Author2, Author3"
  journal: "Journal Name"
  volume: 1
  issue: 2
  pages: "33-40"
  date: "2021"
  doi: "https://doi.org/10.1101/2021.01.01.425865"